name: PR ACTION

on:
    pull_request:
        types: [opened, synchronize]

        branches:
            - dev

env:
    NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install --legacy-peer-deps

            - name: Check format
              run: npm run format

            - name: Lint code
              run: npm run lint

            - name: Test code
              run: npm run test

            - name: Prepare
              run: npm run prepare

            - name: Build the React app
              run: npm run build
