name: PR ACTION

on:
    pull_request:
        types: [opened, synchronize]

        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install

            - name: Check format
              run: npm run format

            - name: Lint code
              run: npm run lint

            - name: Test code
              run: npm run test --api-key="${{ secrets.FIREBASE_API_KEY }}"

            - name: Prepare
              run: npm run prepare

            - name: Build the React app
              run: npm run build
